source $HOME/Dotfiles/vim/vim_config/plugin_config/nerdtree.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/airline.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/delimitmate.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ale.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ycm.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/tsuquyomi.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/rainbowparentheses.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/rooter.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/expand.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/fugitive.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ctrlp.vim
