source ~/Dotfiles/vim/vim_config/plugin_config/nerdtree.vim
source ~/Dotfiles/vim/vim_config/plugin_config/nerdcommenter.vim
source ~/Dotfiles/vim/vim_config/plugin_config/airline.vim
source ~/Dotfiles/vim/vim_config/plugin_config/delimitmate.vim
source ~/Dotfiles/vim/vim_config/plugin_config/ale.vim
source ~/Dotfiles/vim/vim_config/plugin_config/ycm.vim
source ~/Dotfiles/vim/vim_config/plugin_config/tsuquyomi.vim
source ~/Dotfiles/vim/vim_config/plugin_config/rooter.vim
source ~/Dotfiles/vim/vim_config/plugin_config/expand.vim
source ~/Dotfiles/vim/vim_config/plugin_config/fugitive.vim
source ~/Dotfiles/vim/vim_config/plugin_config/fzf.vim
source ~/Dotfiles/vim/vim_config/plugin_config/goyo.vim
source ~/Dotfiles/vim/vim_config/plugin_config/ultisnips.vim
source ~/Dotfiles/vim/vim_config/plugin_config/nerdfonts.vim
source ~/Dotfiles/vim/vim_config/plugin_config/winresizer.vim
source ~/Dotfiles/vim/vim_config/plugin_config/windowswap.vim
source ~/Dotfiles/vim/vim_config/plugin_config/js-file-importer.vim
