source $HOME/Dotfiles/vim/vim_config/plugin_config/nerdtree.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/nerdcommenter.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/airline.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/delimitmate.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ale.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ycm.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/tsuquyomi.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/rainbowparentheses.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/rooter.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/expand.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/fugitive.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ctrlp.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/code-stats.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/ack.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/goyo.vim
source $HOME/Dotfiles/vim/vim_config/plugin_config/nerdfonts.vim
